/* Embeddenator Interop FFI Bindings
 * Auto-generated by cbindgen
 * DO NOT EDIT MANUALLY
 */

#ifndef EMBEDDENATOR_INTEROP_H
#define EMBEDDENATOR_INTEROP_H

/* Generated with cbindgen:0.27.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque handle to a SparseVec
 */
typedef struct SparseVecHandle {
    uint8_t _private[0];
} SparseVecHandle;

/*
 Result buffer for returning data to C
 */
typedef struct ByteBuffer {
    uint8_t *data;
    uintptr_t len;
    uintptr_t capacity;
} ByteBuffer;

/*
 Opaque handle to a ReversibleVSAConfig
 */
typedef struct VSAConfigHandle {
    uint8_t _private[0];
} VSAConfigHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Create a new SparseVec

 # Safety
 Must call `sparse_vec_free` to deallocate
 */
struct SparseVecHandle *sparse_vec_new(void);

/*
 Free a SparseVec

 # Safety
 - `handle` must be a valid pointer from `sparse_vec_new`
 - Must not use `handle` after calling this function
 */
void sparse_vec_free(struct SparseVecHandle *handle);

/*
 Bundle two SparseVecs

 # Safety
 - All handles must be valid
 - Returns a new handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_bundle(const struct SparseVecHandle *a,
                                          const struct SparseVecHandle *b);

/*
 Bind two SparseVecs

 # Safety
 - All handles must be valid
 - Returns a new handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_bind(const struct SparseVecHandle *a,
                                        const struct SparseVecHandle *b);

/*
 Compute cosine similarity between two SparseVecs

 # Safety
 All handles must be valid
 */
double sparse_vec_cosine(const struct SparseVecHandle *a, const struct SparseVecHandle *b);

/*
 Serialize a SparseVec to JSON

 # Safety
 - `handle` must be valid
 - Returns a ByteBuffer that must be freed with `byte_buffer_free`
 */
struct ByteBuffer sparse_vec_to_json(const struct SparseVecHandle *handle);

/*
 Deserialize a SparseVec from JSON

 # Safety
 - `data` must point to valid JSON bytes
 - `len` must be the correct length
 - Returns a handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_from_json(const uint8_t *data, uintptr_t len);

/*
 Create a new default ReversibleVSAConfig

 # Safety
 Must call `vsa_config_free` to deallocate
 */
struct VSAConfigHandle *vsa_config_new(void);

/*
 Create a new ReversibleVSAConfig with custom parameters

 # Safety
 Must call `vsa_config_free` to deallocate
 */
struct VSAConfigHandle *vsa_config_new_custom(uintptr_t block_size,
                                              uintptr_t max_path_depth,
                                              uintptr_t base_shift,
                                              uintptr_t target_sparsity);

/*
 Free a VSAConfig

 # Safety
 - `handle` must be a valid pointer from `vsa_config_new*`
 - Must not use `handle` after calling this function
 */
void vsa_config_free(struct VSAConfigHandle *handle);

/*
 Encode data into a SparseVec

 # Safety
 - All handles must be valid
 - `data` must point to valid bytes
 - `len` must be correct
 - `path` may be null or must be null-terminated UTF-8
 - Returns a handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *vsa_encode_data(const struct VSAConfigHandle *config,
                                        const uint8_t *data,
                                        uintptr_t len,
                                        const char *path);

/*
 Decode a SparseVec back to data

 # Safety
 - All handles must be valid
 - `path` may be null or must be null-terminated UTF-8
 - Returns a ByteBuffer that must be freed with `byte_buffer_free`
 */
struct ByteBuffer vsa_decode_data(const struct VSAConfigHandle *config,
                                  const struct SparseVecHandle *vec,
                                  const char *path,
                                  uintptr_t expected_size);

/*
 Free a ByteBuffer returned by FFI functions

 # Safety
 - `buffer` must be a valid ByteBuffer returned by this library
 - Must not use `buffer` after calling this function
 */
void byte_buffer_free(struct ByteBuffer buffer);

/*
 Get the last error message (if any)

 # Safety
 - Returns a pointer to a static string (do not free)
 - Returns null if no error occurred
 */
const char *embeddenator_last_error(void);

/*
 Create a new SparseVec

 # Safety
 Must call `sparse_vec_free` to deallocate
 */
struct SparseVecHandle *sparse_vec_new(void);

/*
 Free a SparseVec

 # Safety
 - `handle` must be a valid pointer from `sparse_vec_new`
 - Must not use `handle` after calling this function
 */
void sparse_vec_free(struct SparseVecHandle *handle);

/*
 Bundle two SparseVecs

 # Safety
 - All handles must be valid
 - Returns a new handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_bundle(const struct SparseVecHandle *a,
                                          const struct SparseVecHandle *b);

/*
 Bind two SparseVecs

 # Safety
 - All handles must be valid
 - Returns a new handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_bind(const struct SparseVecHandle *a,
                                        const struct SparseVecHandle *b);

/*
 Compute cosine similarity between two SparseVecs

 # Safety
 All handles must be valid
 */
double sparse_vec_cosine(const struct SparseVecHandle *a, const struct SparseVecHandle *b);

/*
 Serialize a SparseVec to JSON

 # Safety
 - `handle` must be valid
 - Returns a ByteBuffer that must be freed with `byte_buffer_free`
 */
struct ByteBuffer sparse_vec_to_json(const struct SparseVecHandle *handle);

/*
 Deserialize a SparseVec from JSON

 # Safety
 - `data` must point to valid JSON bytes
 - `len` must be the correct length
 - Returns a handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *sparse_vec_from_json(const uint8_t *data, uintptr_t len);

/*
 Create a new default ReversibleVSAConfig

 # Safety
 Must call `vsa_config_free` to deallocate
 */
struct VSAConfigHandle *vsa_config_new(void);

/*
 Create a new ReversibleVSAConfig with custom parameters

 # Safety
 Must call `vsa_config_free` to deallocate
 */
struct VSAConfigHandle *vsa_config_new_custom(uintptr_t block_size,
                                              uintptr_t max_path_depth,
                                              uintptr_t base_shift,
                                              uintptr_t target_sparsity);

/*
 Free a VSAConfig

 # Safety
 - `handle` must be a valid pointer from `vsa_config_new*`
 - Must not use `handle` after calling this function
 */
void vsa_config_free(struct VSAConfigHandle *handle);

/*
 Encode data into a SparseVec

 # Safety
 - All handles must be valid
 - `data` must point to valid bytes
 - `len` must be correct
 - `path` may be null or must be null-terminated UTF-8
 - Returns a handle that must be freed with `sparse_vec_free`
 */
struct SparseVecHandle *vsa_encode_data(const struct VSAConfigHandle *config,
                                        const uint8_t *data,
                                        uintptr_t len,
                                        const char *path);

/*
 Decode a SparseVec back to data

 # Safety
 - All handles must be valid
 - `path` may be null or must be null-terminated UTF-8
 - Returns a ByteBuffer that must be freed with `byte_buffer_free`
 */
struct ByteBuffer vsa_decode_data(const struct VSAConfigHandle *config,
                                  const struct SparseVecHandle *vec,
                                  const char *path,
                                  uintptr_t expected_size);

/*
 Free a ByteBuffer returned by FFI functions

 # Safety
 - `buffer` must be a valid ByteBuffer returned by this library
 - Must not use `buffer` after calling this function
 */
void byte_buffer_free(struct ByteBuffer buffer);

/*
 Get the last error message (if any)

 # Safety
 - Returns a pointer to a static string (do not free)
 - Returns null if no error occurred
 */
const char *embeddenator_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMBEDDENATOR_INTEROP_H */
